pipeline {
    agent any

    stages {
        stage('CI - Test') {
            agent {
                docker { image 'python:3.6-slim' }
            }
            steps {
                sh 'pip install -r requirements.txt'
                sh 'pytest -q'
            }
        }

        stage('CI - Docker Build') {
            steps {
                sh 'docker build -t devops-python-app -f Dockerfile .'
            }
        }

        stage('CD - Deploy') {
            when {
                anyOf {
                    branch 'develop'
                    branch 'master'
                }
            }
            steps {
                sh 'docker compose -f docker-compose.yml up -d'
                sh 'sleep 20'
                sh 'docker run --rm --network vops-training-python-app_develop_scalian_training curlimages/curl curl -f http://my-flask-app-dc:5000/'
                sh 'docker compose -f docker-compose.yml down --volumes'
            }
        }
    }
}