pipeline {
    agent any

    stages {
        stage('CI - Test') {
            agent {
                docker { image 'python:3.6-slim' }
            }
            steps {
                sh 'pip install -r requirements.txt'
                sh 'pytest -q'
            }
        }

        stage('CI - Docker Build') {
            steps {
                sh 'docker build -t devops-python-app -f devops/Dockerfile .'
            }
        }
    }
}