pipeline {
    agent any

    stages {
        stage('CI - Test') {
            agent {
                docker { image 'python:3.6-slim' }
            }
            steps {
                sh 'pip install -r requirements.txt'
                sh 'pytest -q'
            }
        }

        stage('CI - Docker Build') {
            steps {
                sh 'docker build -t devops-python-app -f Dockerfile .'
            }
        }

        stage('CD - Deploy') {
            when {
                anyOf {
                    branch 'develop'
                    branch 'master'
                }
            }
            steps {
                sh 'docker compose -f docker-compose.yml up -d'
                sh 'sleep 20'
                sh '''
                    APP_IP=$(docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" my-flask-app-dc)
                    curl -f http://$APP_IP:5000/health
                '''
                sh 'docker compose -f docker-compose.yml down --volumes'
            }
        }
    }
}